TIME_SCALE_ACCELERATED = 100
AI_ONLY_BOOL = 1
DISPLAY_GRAPHICS_BOOL = 1
DISPLAY_W = 600
DISPLAY_H = 600
FPS = 30
BG_IMAGE_FILE = "images/BG.png"

DATA_FONT_SIZE = 18
DATA_FONT_COLOR =  (255,255,255)

IMAGE_START_ANGLE = 0

PLAYER_IMAGE_FILE = "player_image.png"
PLAYER_ROTATE_RATE = 0.5

ACTION_SPACE_N = 2
CLOCKWISE = -1
COUNTER_CLOCKWISE = 1

TARGET_IMAGE_FILE = "dead.png"
TARGET_COOLDOWN_TIME = 5000

GENERATION_POPULATION = 3
ITERATION_TIME = 5000
NUM_INPUTS = 2
NUM_HIDDEN_1 = 3
NUM_HIDDEN_2 = 3
NUM_OUTPUTS = 2