DISPLAY_W = 600
DISPLAY_H = 600
FPS = 30
BG_IMAGE_FILE = "images/BG.png"

DATA_FONT_SIZE = 18
DATA_FONT_COLOR =  (255,255,255)

IMAGE_START_ANGLE = 0

PLAYER_IMAGE_FILE = "player_image.png"
PLAYER_ROTATE_RATE = 0.3
CLOCKWISE = -1
COUNTER_CLOCKWISE = 1

TARGET_IMAGE_FILE = "dead.png"
TARGET_COOLDOWN_TIME = 5000

GENERATION_POPULATION = 20
ITERATION_TIME = 10000
MUTATION_WEIGHT_MODIFY_CHANCE = 0.2
MUTATION_MATRIX_MIX_PERC = 0.5
MUTATION_CUT_OFF = 0.4
MUTATION_BAD_TO_KEEP = 0.2
NUM_INPUTS = 3
NUM_HIDDEN_1 = 4
NUM_HIDDEN_2 = 4
NUM_OUTPUTS = 2